version: '3.8'

services:
  web:
    build:
      context: ./
    volumes:
      - .:/app
    command: node src/app.js
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: fakepassword
      DB_NAME: rrrewear
      PORT: 3000
      NODE_ENV: development
      SESSION_SECRET: your_session_secret_key_here
    restart: unless-stopped
    networks:
      - app-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: fakepassword
      MYSQL_DATABASE: rrrewear
    ports:
      - "3307:3306"
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/init.sql:/docker-entrypoint-initdb.d/02-init.sql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: fakepassword
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
