version: '3.3'
services:
  web:
    build:
      context: ./
    volumes:
      - .:/src
    command: supervisor -e 'js,pug,html' index.js
    ports:
      - "3003:3003"
    depends_on:
      - db
    env_file:
      - ./.env
  db:
    image: mysql:9.2
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=sd2-db
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    ports:
      - "8081:80"
    depends_on:
      - db
